# .github/workflows/dockerbased.yml
name: Run DEV Tests in Docker

on:
  push:
    branches: [main]
    paths:
      - 'tests/**'
      - 'configs/playwright.dev.config.ts'
      - 'utils/testConfig.ts'
      - '.github/workflows/dockerbased.yml'
      - 'Dockerfile'
  pull_request:
    branches: [main]
  workflow_dispatch:  # manual trigger from GitHub UI

jobs:
  test:
    name: Run DEV Tests Inside Docker
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t playwright-tests .

      - name: Run Tests Inside Docker
        run: |
          docker run --rm \
            -e CI=true \
            -e DISPLAY= \
            -v ${{ github.workspace }}/allure-report:/app/allure-report \
            playwright-tests \
            npm run ci:dev

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-dev
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          destination_dir: dev
